const C=window.APP_CONFIG;
const $=id=>document.getElementById(id);
const state={containers:[],container:null,team:null,pallet:null,captures:[],timer:null,photos:{item:'',master:''},reusedPhotos:{item:'',master:''},reuseSourceCaptureId:'',stream:null,cameraMode:'',cameraTarget:'',zxingControls:null,connection:null,syncFailures:0,syncInFlight:false,lastSync:0,draftTimer:null,lookupTimer:null,lookupSequence:0,lastLookupKey:''};
const fields=['captureId','internalRef','ean','description','boxCount','pieces','color','size','height','length','width','masterHeight','masterLength','masterWidth','notes'];
const SESSION_KEY='validatorSessionV240',DB_NAME='ValidadorContenedores',DB_STORE='drafts';

document.addEventListener('DOMContentLoaded',()=>{ $('version').textContent='v'+C.VERSION; $('person').value=localStorage.getItem('validatorName')||''; bind(); bootstrap(); });
function bind(){
  $('showContainerBtn').onclick=()=>$('newContainerCard').classList.toggle('hidden');
  $('createContainerBtn').onclick=createContainer; $('joinBtn').onclick=joinTeam; $('newPalletBtn').onclick=createPallet;
  $('exitTeamBtn').onclick=()=>{localStorage.removeItem(SESSION_KEY);location.reload()}; $('backPalletsBtn').onclick=showPallets; $('clearBtn').onclick=clearForm;
  $('saveBtn').onclick=saveCapture; $('deleteBtn').onclick=deleteCapture; $('refreshBtn').onclick=refreshPallet; $('finishBtn').onclick=finalizePallet;
  document.querySelectorAll('.scan').forEach(b=>b.onclick=()=>openScanner(b.dataset.target));
  document.querySelectorAll('.camera').forEach(b=>b.onclick=()=>openPhotoCamera(b.dataset.photo));
  document.querySelectorAll('.gallery').forEach(b=>b.onclick=()=>$(`${b.dataset.photo}Upload`).click());
  $('itemUpload').onchange=e=>loadFile(e.target.files[0],'item'); $('masterUpload').onchange=e=>loadFile(e.target.files[0],'master');
  $('closeCameraBtn').onclick=closeCamera; $('snapBtn').onclick=snapPhoto;
  $('scanUpload').onchange=e=>decodeScanPhoto(e.target.files[0]);
  fields.filter(x=>x!=='captureId').forEach(id=>$(id).addEventListener('input',scheduleDraft));
  ['internalRef','ean'].forEach(id=>$(id).addEventListener('input',scheduleItemLookup));
  document.addEventListener('visibilitychange',()=>{if(document.hidden)saveDraft().catch(()=>{});else if(state.pallet)refreshPallet();});
  window.addEventListener('pagehide',()=>saveDraft().catch(()=>{}));
  window.addEventListener('online',()=>{setConnection('connecting');if(state.pallet)refreshPallet();else bootstrap(true)});window.addEventListener('offline',()=>setConnection('offline'));
}
async function bootstrap(silent=false){try{assertConfig();if(!silent)setConnection('connecting');const r=await jsonp('bootstrap');state.containers=r.containers||[];state.connection=r.connection||null;connectionSuccess();renderContainers();if(!silent)await restoreSession();}catch(e){connectionFailure(!state.lastSync);if(!silent)error(e)}}
function assertConfig(){if(!C.API_URL||C.API_URL.includes('PEGA_AQUI'))throw Error('Falta pegar la URL /exec de Apps Script en config.js');}
function renderContainers(){ $('containerSelect').innerHTML='<option value="">Selecciona…</option>'+state.containers.map(c=>`<option value="${c.ID_CONTENEDOR}">${esc(c.REFERENCIA_CONTENEDOR)}</option>`).join(''); }
async function createContainer(){try{const reference=$('containerRef').value.trim();if(!reference)throw Error('Escribe la referencia del contenedor.');busy('Creando contenedor…');const r=await post('createContainer',{reference,purchaseOrder:$('purchaseOrder').value});state.containers.push(r.container);renderContainers();$('containerSelect').value=r.container.ID_CONTENEDOR;$('newContainerCard').classList.add('hidden');toast('Contenedor creado');}catch(e){error(e)}finally{busy(false)}}
async function joinTeam(){try{const person=$('person').value.trim(),teamName=$('teamName').value.trim(),containerId=$('containerSelect').value;if(!person||!teamName||!containerId)throw Error('Completa nombre, equipo y contenedor.');busy('Abriendo equipo…');const r=await post('openTeam',{person,teamName,containerId});localStorage.setItem('validatorName',person);state.container=state.containers.find(c=>c.ID_CONTENEDOR===containerId);state.team=r.team;saveSession();showPalletScreen();await loadPallets();}catch(e){error(e)}finally{busy(false)}}
function showPalletScreen(){show('screenPallets');$('containerName').textContent=state.container.REFERENCIA_CONTENEDOR;$('teamLabel').textContent=state.team.NOMBRE_EQUIPO;$('palletMenu').open=false;}
async function loadPallets(){const r=await jsonp('listPallets',{containerId:state.container.ID_CONTENEDOR,teamId:state.team.ID_EQUIPO}),pallets=r.pallets||[],finished=pallets.filter(p=>p.ESTADO==='FINALIZADA'),inProcess=pallets.filter(p=>p.ESTADO!=='FINALIZADA');$('palletCount').textContent=pallets.length;$('palletTotal').textContent=pallets.length;$('palletInProcess').textContent=inProcess.length;$('palletFinalized').textContent=finished.length;$('palletList').innerHTML=palletGroup('Tarimas en proceso',inProcess,'process')+palletGroup('Tarimas finalizadas',finished,'final');document.querySelectorAll('[data-pallet]').forEach(b=>b.onclick=()=>openPallet(b.dataset.pallet));}
function palletGroup(title,pallets,kind){const rows=pallets.length?pallets.map(p=>{const own=p.ID_EQUIPO===state.team.ID_EQUIPO;return`<div class="list-row pallet-row"><div class="thumb pallet-icon">📦</div><div><div class="row-title">${esc(p.CODIGO_TARIMA)}</div><div class="row-meta">ID ${esc(p.ID_TARIMA)} · ${esc(p.ESTADO)} · ${esc(p.CREADO_POR)}${own?' · Tu equipo':' · Otro equipo'}</div></div>${own?`<button class="row-action" data-pallet="${p.ID_TARIMA}" aria-label="Abrir tarima ${escAttr(p.CODIGO_TARIMA)}">›</button>`:'<span class="other-team" title="Solo el equipo propietario puede abrirla">Vista</span>'}</div>`}).join(''):'<p class="empty-group">Sin tarimas en este estado</p>';return`<section class="pallet-group ${kind}"><h3>${title}<span>${pallets.length}</span></h3>${rows}</section>`;}
async function createPallet(){try{busy('Generando tarima…');const r=await post('createPallet',{containerId:state.container.ID_CONTENEDOR,teamId:state.team.ID_EQUIPO,person:$('person').value});await openPallet(r.pallet.ID_TARIMA);}catch(e){error(e)}finally{busy(false)}}
async function openPallet(id){state.pallet={ID_TARIMA:id};saveSession();show('screenCapture');$('palletIdLabel').textContent='ID '+id;$('syncText').textContent='Cargando registros…';await Promise.allSettled([refreshPallet(),restoreDraft(id)]);clearInterval(state.timer);state.timer=setInterval(refreshPallet,Math.max(5000,Number(C.REFRESH_MS)||5000));}
async function refreshPallet(){if(!state.pallet||state.syncInFlight||document.hidden)return;state.syncInFlight=true;try{const r=await jsonp('getPallet',{palletId:state.pallet.ID_TARIMA,teamId:state.team.ID_EQUIPO});state.pallet=r.pallet;state.captures=r.captures||[];renderPallet(r);connectionSuccess();}catch(e){connectionFailure();$('syncText').textContent=state.syncFailures<3?'Reintentando sincronización…':'Sin conexión · tus datos permanecen guardados';}finally{state.syncInFlight=false}}
function renderPallet(r){$('palletCode').textContent=r.pallet.CODIGO_TARIMA;$('palletIdLabel').textContent='ID '+r.pallet.ID_TARIMA;$('palletStatus').textContent=r.pallet.ESTADO;$('boxTotal').textContent=r.totals.boxes;$('pieceTotal').textContent=r.totals.pieces;$('syncText').textContent='Actualizado '+new Date().toLocaleTimeString();const open=r.pallet.ESTADO==='EN PROCESO';$('captureCard').classList.toggle('hidden',!open);$('finishBtn').classList.toggle('hidden',!open);$('captureList').innerHTML=state.captures.map(x=>{const boxes=captureBoxes(x),total=boxes*Number(x.PIEZAS_CAJA||0);return`<div class="list-row"><img class="thumb" src="${escAttr(x.FOTO_ITEM_URL)}"><div><div class="row-title">${esc(x.DESCRIPCION)}</div><div class="row-meta">Registro ${x.NUMERO_CAJA} · ${boxes} ${boxes===1?'caja':'cajas'} · ${x.PIEZAS_CAJA} pzas/caja · ${total} pzas total<br>${esc(x.REFERENCIA_INTERNA||x.EAN)} · ${esc(x.VALIDADOR)}</div></div>${open?`<button class="row-action edit-record" data-id="${x.ID_CAPTURA}">✎</button>`:''}</div>`}).join('');document.querySelectorAll('.edit-record').forEach(b=>b.onclick=()=>editCapture(b.dataset.id));}
function editCapture(id){const x=state.captures.find(r=>r.ID_CAPTURA===id),map={captureId:'ID_CAPTURA',internalRef:'REFERENCIA_INTERNA',ean:'EAN',description:'DESCRIPCION',boxCount:'CANTIDAD_CAJAS',pieces:'PIEZAS_CAJA',color:'COLOR',size:'TALLA',height:'ALTO_ITEM_CM',length:'LARGO_ITEM_CM',width:'ANCHO_ITEM_CM',masterHeight:'ALTO_MASTER_CM',masterLength:'LARGO_MASTER_CM',masterWidth:'ANCHO_MASTER_CM',notes:'OBSERVACIONES'};fields.forEach(f=>$(f).value=x[map[f]]||'');$('boxCount').value=captureBoxes(x);state.photos={item:'',master:''};state.reusedPhotos={item:'',master:''};state.reuseSourceCaptureId='';state.lastLookupKey='';hideReuseNotice();preview('item',x.FOTO_ITEM_URL);preview('master',x.FOTO_MASTER_URL);$('deleteBtn').classList.remove('hidden');$('captureTitle').textContent='Editar registro '+x.NUMERO_CAJA;scheduleDraft();$('captureCard').scrollIntoView({behavior:'smooth'});}
async function saveCapture(){try{const payload={captureId:$('captureId').value,palletId:state.pallet.ID_TARIMA,teamId:state.team.ID_EQUIPO,person:$('person').value,internalRef:$('internalRef').value,ean:$('ean').value,description:$('description').value,boxCount:$('boxCount').value,pieces:$('pieces').value,color:$('color').value,size:$('size').value,height:$('height').value,length:$('length').value,width:$('width').value,masterHeight:$('masterHeight').value,masterLength:$('masterLength').value,masterWidth:$('masterWidth').value,notes:$('notes').value,itemPhoto:state.photos.item,masterPhoto:state.photos.master,reuseSourceCaptureId:state.reuseSourceCaptureId};if(!payload.internalRef.trim()&&!payload.ean.trim())throw Error('Escanea o escribe la referencia interna o el EAN.');if(!payload.description.trim()||Number(payload.pieces)<1)throw Error('Completa descripción y piezas por caja.');if(!Number.isInteger(Number(payload.boxCount))||Number(payload.boxCount)<1)throw Error('La cantidad de cajas debe ser un número entero mayor a cero.');if(!payload.captureId&&(!payload.itemPhoto&&!state.reusedPhotos.item||!payload.masterPhoto&&!state.reusedPhotos.master))throw Error('Toma las dos fotografías obligatorias o recupera una ficha existente.');await saveDraft().catch(()=>{});optimistic(payload);busy('Guardando '+payload.boxCount+' caja(s) y fotografías…');await post('saveCapture',payload,120000);await clearForm();await refreshPallet();toast(payload.boxCount+' caja(s) guardadas');}catch(e){error(e);await refreshPallet()}finally{busy(false)}}
async function deleteCapture(){const captureId=$('captureId').value;if(!captureId)return;const item=state.captures.find(x=>x.ID_CAPTURA===captureId),name=item?.DESCRIPCION||'este item';if(!confirm('¿Estás seguro que quieres eliminar este registro (item): "'+name+'"?'))return;try{busy('Eliminando registro…');await post('deleteCapture',{captureId,palletId:state.pallet.ID_TARIMA,teamId:state.team.ID_EQUIPO,person:$('person').value});await clearForm();await refreshPallet();toast('Registro eliminado de la tarima');}catch(e){error(e);await refreshPallet()}finally{busy(false)}}
function optimistic(p){state.captures.push({ID_CAPTURA:'TEMP',DESCRIPCION:p.description,CANTIDAD_CAJAS:Number(p.boxCount),PIEZAS_CAJA:p.pieces,REFERENCIA_INTERNA:p.internalRef,EAN:p.ean,VALIDADOR:p.person,FOTO_ITEM_URL:p.itemPhoto||state.reusedPhotos.item,NUMERO_CAJA:'…'});renderPallet({pallet:state.pallet,captures:state.captures,totals:{boxes:state.captures.reduce((n,x)=>n+captureBoxes(x),0),pieces:state.captures.reduce((n,x)=>n+Number(x.PIEZAS_CAJA||0)*captureBoxes(x),0)}});}
async function finalizePallet(){if(!confirm('¿Finalizar y bloquear esta tarima?'))return;try{busy('Consolidando tarima…');await post('finalizePallet',{palletId:state.pallet.ID_TARIMA,teamId:state.team.ID_EQUIPO,person:$('person').value},90000);await deleteDraft(state.pallet.ID_TARIMA);await refreshPallet();toast('Tarima finalizada');}catch(e){error(e)}finally{busy(false)}}
async function showPallets(){await saveDraft().catch(()=>{});clearInterval(state.timer);state.pallet=null;saveSession();showPalletScreen();loadPallets().catch(error)}function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.add('hidden'));$(id).classList.remove('hidden');window.scrollTo(0,0)}
async function clearForm(){clearTimeout(state.draftTimer);clearTimeout(state.lookupTimer);state.lookupSequence++;const palletId=state.pallet?.ID_TARIMA;fields.forEach(f=>$(f).value='');$('boxCount').value='1';state.photos={item:'',master:''};state.reusedPhotos={item:'',master:''};state.reuseSourceCaptureId='';state.lastLookupKey='';hideReuseNotice();['item','master'].forEach(k=>$(`${k}Preview`).innerHTML='<span>Sin foto</span>');$('deleteBtn').classList.add('hidden');$('captureTitle').textContent='Capturar caja(s)';if(palletId)await deleteDraft(palletId)}
async function loadFile(file,type){if(!file)return;state.photos[type]=await compress(file);preview(type,state.photos[type]);await saveDraft().catch(()=>{});}
async function openPhotoCamera(type){state.cameraMode='photo';state.cameraTarget=type;$('cameraModal').classList.add('photo-mode');$('cameraHint').textContent='Fotografía de '+(type==='item'?'artículo':'caja máster')+' · alta calidad';$('snapBtn').classList.remove('hidden');await openCamera();}
async function openScanner(target){state.cameraMode='scan';state.cameraTarget=target;$('cameraModal').classList.remove('photo-mode');$('cameraHint').textContent='Centra el código de números y/o letras';$('snapBtn').classList.add('hidden');try{if('BarcodeDetector'in window){await openCamera();scanLoop();return}if(!window.ZXingBrowser)throw Error('No se cargó el lector de códigos');$('cameraModal').classList.remove('hidden');const reader=new ZXingBrowser.BrowserMultiFormatReader();state.zxingControls=await reader.decodeFromVideoDevice(undefined,$('cameraVideo'),(result,err,controls)=>{if(result){$(state.cameraTarget).value=result.getText();scheduleDraft();scheduleItemLookup(true);navigator.vibrate?.(100);controls.stop();state.zxingControls=null;closeCamera();toast('Código alfanumérico escaneado')}});}catch(e){closeCamera();toast('La cámara continua fue bloqueada. Toma una foto clara del código.');$('scanUpload').value='';$('scanUpload').click()}}
async function decodeScanPhoto(file){if(!file)return;try{busy('Leyendo código…');if(!window.ZXingBrowser)throw Error('No se cargó el lector');const data=await compress(file),reader=new ZXingBrowser.BrowserMultiFormatReader(),result=await reader.decodeFromImageUrl(data);$(state.cameraTarget).value=result.getText();scheduleDraft();scheduleItemLookup(true);navigator.vibrate?.(100);toast('Código escaneado');}catch(e){error(new Error('No se detectó un código. Acerca la cámara y evita reflejos.'))}finally{busy(false)}}
async function openCamera(){try{$('cameraModal').classList.remove('hidden');state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});$('cameraVideo').srcObject=state.stream;}catch(e){closeCamera();throw Error('No se pudo abrir la cámara. Revisa el permiso del navegador.')}}
async function scanLoop(){try{const wanted=['ean_13','ean_8','upc_a','upc_e','code_128','code_39','code_93','codabar','itf','qr_code','data_matrix','pdf417','aztec'],supported=typeof BarcodeDetector.getSupportedFormats==='function'?await BarcodeDetector.getSupportedFormats():wanted,formats=wanted.filter(x=>supported.includes(x));if(!formats.length)throw Error('Sin formatos compatibles');const detector=new BarcodeDetector({formats});while(state.stream&&state.cameraMode==='scan'){try{const codes=await detector.detect($('cameraVideo'));if(codes.length){$(state.cameraTarget).value=codes[0].rawValue;scheduleDraft();scheduleItemLookup(true);navigator.vibrate?.(100);closeCamera();toast('Código alfanumérico escaneado');return}}catch(e){}await wait(150)}}catch(e){closeCamera();toast('Toma una foto clara del código de números o letras.');$('scanUpload').value='';$('scanUpload').click()}}
function snapPhoto(){const v=$('cameraVideo'),c=document.createElement('canvas'),max=1800,scale=Math.min(1,max/Math.max(v.videoWidth,v.videoHeight));c.width=Math.round(v.videoWidth*scale);c.height=Math.round(v.videoHeight*scale);const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(v,0,0,c.width,c.height);const data=c.toDataURL('image/jpeg',.88);state.photos[state.cameraTarget]=data;preview(state.cameraTarget,data);saveDraft().catch(()=>{});closeCamera();}
function closeCamera(){if(state.zxingControls){try{state.zxingControls.stop()}catch(e){}state.zxingControls=null}if(state.stream)state.stream.getTracks().forEach(t=>t.stop());state.stream=null;$('cameraModal').classList.add('hidden');$('cameraModal').classList.remove('photo-mode')}
function preview(type,data){$(`${type}Preview`).innerHTML=`<img src="${data}" alt="Vista previa">`}
function captureBoxes(x){const n=Number(x.CANTIDAD_CAJAS||1);return Number.isInteger(n)&&n>0?n:1}
function compress(file){return new Promise((res,rej)=>{const img=new Image(),u=URL.createObjectURL(file);img.onload=()=>{const max=1800,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',.88))};img.onerror=rej;img.src=u})}
function scheduleItemLookup(immediate=false){if($('captureId').value||!state.pallet)return;clearTimeout(state.lookupTimer);const sequence=++state.lookupSequence;state.lookupTimer=setTimeout(()=>lookupItem(sequence),immediate?0:650)}
async function lookupItem(sequence){const internalRef=$('internalRef').value.trim(),ean=$('ean').value.trim(),key=internalRef.toUpperCase()+'|'+ean.toUpperCase();if(!internalRef&&!ean||key===state.lastLookupKey||$('captureId').value)return;state.lastLookupKey=key;try{const r=await jsonp('lookupItem',{palletId:state.pallet.ID_TARIMA,teamId:state.team.ID_EQUIPO,internalRef,ean},1);if(sequence!==state.lookupSequence||!r.found||$('captureId').value)return;applyItemProfile(r.profile)}catch(e){if(sequence===state.lookupSequence)state.lastLookupKey=''}}
function applyItemProfile(p){const map={internalRef:'internalRef',ean:'ean',description:'description',color:'color',size:'size',height:'height',length:'length',width:'width',masterHeight:'masterHeight',masterLength:'masterLength',masterWidth:'masterWidth'};Object.entries(map).forEach(([id,key])=>$(id).value=p[key]??'');state.reusedPhotos={item:p.itemPhotoUrl||'',master:p.masterPhotoUrl||''};state.reuseSourceCaptureId=p.sourceCaptureId||'';const itemPreview=state.photos.item||state.reusedPhotos.item,masterPreview=state.photos.master||state.reusedPhotos.master;if(itemPreview)preview('item',itemPreview);if(masterPreview)preview('master',masterPreview);$('itemReuseText').textContent='Datos y fotos tomados de '+(p.sourcePalletCode||'una captura anterior')+'. Sólo completa cajas y piezas por caja; puedes editar cualquier dato.';$('itemReuseNotice').classList.remove('hidden');scheduleDraft();toast('Ficha del artículo autocompletada')}
function hideReuseNotice(){$('itemReuseNotice').classList.add('hidden');$('itemReuseText').textContent='Revisa los datos y edita lo necesario.'}
function saveSession(){if(!state.container||!state.team){localStorage.removeItem(SESSION_KEY);return}localStorage.setItem(SESSION_KEY,JSON.stringify({containerId:state.container.ID_CONTENEDOR,team:state.team,palletId:state.pallet?.ID_TARIMA||'',savedAt:Date.now()}))}
async function restoreSession(){try{const s=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');if(!s||Date.now()-Number(s.savedAt||0)>86400000)return;const container=state.containers.find(x=>x.ID_CONTENEDOR===s.containerId);if(!container||!s.team?.ID_EQUIPO)return;state.container=container;state.team=s.team;$('person').value=localStorage.getItem('validatorName')||s.team.CREADO_POR||'';showPalletScreen();if(s.palletId)await openPallet(s.palletId);else await loadPallets();}catch(e){localStorage.removeItem(SESSION_KEY)}}
function scheduleDraft(){clearTimeout(state.draftTimer);state.draftTimer=setTimeout(()=>saveDraft().catch(()=>{}),350)}
function draftData(){return{palletId:state.pallet?.ID_TARIMA||'',fields:Object.fromEntries(fields.map(id=>[id,$(id).value])),photos:{...state.photos},reusedPhotos:{...state.reusedPhotos},reuseSourceCaptureId:state.reuseSourceCaptureId,savedAt:Date.now()}}
async function saveDraft(){if(!state.pallet)return;const draft=draftData(),hasText=Object.entries(draft.fields).some(([k,v])=>k!=='boxCount'&&String(v||'').trim())||String(draft.fields.boxCount||'')!=='1',hasPhotos=!!(draft.photos.item||draft.photos.master||draft.reusedPhotos.item||draft.reusedPhotos.master);if(!hasText&&!hasPhotos){await deleteDraft(draft.palletId);return}await dbRequest('put',draft)}
async function restoreDraft(palletId){try{const d=await dbRequest('get',palletId);if(!d||d.palletId!==palletId)return;fields.forEach(id=>$(id).value=d.fields?.[id]??'');if(!$('boxCount').value)$('boxCount').value='1';state.photos={item:d.photos?.item||'',master:d.photos?.master||''};state.reusedPhotos={item:d.reusedPhotos?.item||'',master:d.reusedPhotos?.master||''};state.reuseSourceCaptureId=d.reuseSourceCaptureId||'';const itemPreview=state.photos.item||state.reusedPhotos.item,masterPreview=state.photos.master||state.reusedPhotos.master;if(itemPreview)preview('item',itemPreview);if(masterPreview)preview('master',masterPreview);if(state.reuseSourceCaptureId){$('itemReuseText').textContent='Ficha recuperada del borrador. Sólo completa cajas y piezas por caja; puedes editar cualquier dato.';$('itemReuseNotice').classList.remove('hidden')}else hideReuseNotice();$('deleteBtn').classList.toggle('hidden',!$('captureId').value);$('captureTitle').textContent=$('captureId').value?'Editar registro recuperado':'Capturar caja(s) · borrador recuperado';toast('Borrador recuperado con tus datos y fotografías');}catch(e){console.warn('No se pudo recuperar el borrador',e)}}
function deleteDraft(palletId){return dbRequest('delete',palletId).catch(()=>{})}
function dbRequest(mode,value){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(DB_STORE))db.createObjectStore(DB_STORE,{keyPath:'palletId'})};req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result,tx=db.transaction(DB_STORE,'readwrite'),store=tx.objectStore(DB_STORE),op=mode==='put'?store.put(value):mode==='get'?store.get(value):store.delete(value);op.onsuccess=()=>resolve(op.result);op.onerror=()=>reject(op.error);tx.oncomplete=()=>db.close()}})}
async function post(action,payload,timeout=60000){const tx=crypto.randomUUID();submitPost(action,tx,payload);const start=Date.now();let delay=700;while(Date.now()-start<timeout){let r=null;try{r=await jsonp('job',{tx},1)}catch(e){setConnection(navigator.onLine?'retrying':'offline')}if(r?.status==='done'){if(!r.ok)throw Error(r.error||'Error de servidor');connectionSuccess();return r.result}await wait(delay);delay=Math.min(1800,delay+150)}throw Error('La operación sigue pendiente. El borrador permanece guardado; revisa la conexión y vuelve a intentar.');}
function submitPost(action,tx,payload){const frame=document.createElement('iframe'),form=document.createElement('form');frame.name='post_'+tx;frame.hidden=true;form.hidden=true;form.method='POST';form.action=C.API_URL;form.target=frame.name;Object.entries({action,tx,payload:JSON.stringify(payload)}).forEach(([name,value])=>{const input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;form.appendChild(input)});document.body.append(frame,form);form.submit();setTimeout(()=>{form.remove();frame.remove()},120000)}
async function jsonp(action,params={},attempts=2){let last;for(let i=0;i<attempts;i++){try{const data=await jsonpOnce(action,params);connectionSuccess();return data}catch(e){last=e;if(i<attempts-1)await wait(700)}}throw last}
function jsonpOnce(action,params={}){return new Promise((resolve,reject)=>{const cb='cb_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script'),timer=setTimeout(()=>done(new Error('Sin respuesta del servidor')),12000);window[cb]=data=>done(null,data);function done(err,data){clearTimeout(timer);delete window[cb];s.remove();err?reject(err):data?.ok===false?reject(new Error(data.error||'Error')):resolve(data)}const q=new URLSearchParams({action,prefix:cb,...params,_:Date.now()});s.onerror=()=>done(new Error('No se pudo conectar con Apps Script'));s.src=C.API_URL+'?'+q;s.async=true;document.body.appendChild(s)})}
function connectionSuccess(){state.syncFailures=0;state.lastSync=Date.now();setConnection('online',state.connection?.spreadsheetName)}function connectionFailure(immediate=false){state.syncFailures++;if(immediate||!navigator.onLine||state.syncFailures>=3)setConnection('offline');else setConnection('retrying')}
function setConnection(status,label=''){const el=$('online'),map={online:['● '+(label||'Sincronizado'),'#9be5c8'],connecting:['● Conectando…','#ffe08a'],retrying:['● Reintentando…','#ffe08a'],offline:['● Sin conexión','#ff9b9b']},v=map[status]||map.connecting;el.textContent=v[0];el.style.color=v[1]}
function busy(text){$('busy').classList.toggle('hidden',!text);if(text)$('busyText').textContent=text}function toast(m){$('toast').textContent=m;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),3500)}function error(e){console.error(e);toast(e.message||String(e))}function wait(ms){return new Promise(r=>setTimeout(r,ms))}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escAttr(v){return esc(v)}
