const C=window.APP_CONFIG;
const $=id=>document.getElementById(id);
const state={containers:[],container:null,team:null,pallet:null,captures:[],timer:null,photos:{item:'',master:''},stream:null,cameraMode:'',cameraTarget:'',zxingControls:null,connection:null};
const fields=['captureId','internalRef','ean','description','pieces','color','size','height','length','width','notes'];

document.addEventListener('DOMContentLoaded',()=>{ $('version').textContent='v'+C.VERSION; $('person').value=localStorage.getItem('validatorName')||''; bind(); bootstrap(); });
function bind(){
  $('showContainerBtn').onclick=()=>$('newContainerCard').classList.toggle('hidden');
  $('createContainerBtn').onclick=createContainer; $('joinBtn').onclick=joinTeam; $('newPalletBtn').onclick=createPallet;
  $('exitTeamBtn').onclick=()=>location.reload(); $('backPalletsBtn').onclick=showPallets; $('clearBtn').onclick=clearForm;
  $('saveBtn').onclick=saveCapture; $('refreshBtn').onclick=refreshPallet; $('finishBtn').onclick=finalizePallet;
  document.querySelectorAll('.scan').forEach(b=>b.onclick=()=>openScanner(b.dataset.target));
  document.querySelectorAll('.camera').forEach(b=>b.onclick=()=>openPhotoCamera(b.dataset.photo));
  document.querySelectorAll('.gallery').forEach(b=>b.onclick=()=>$(`${b.dataset.photo}Upload`).click());
  $('itemUpload').onchange=e=>loadFile(e.target.files[0],'item'); $('masterUpload').onchange=e=>loadFile(e.target.files[0],'master');
  $('closeCameraBtn').onclick=closeCamera; $('snapBtn').onclick=snapPhoto;
  $('scanUpload').onchange=e=>decodeScanPhoto(e.target.files[0]);
  window.addEventListener('online',()=>setOnline(true)); window.addEventListener('offline',()=>setOnline(false));
}
async function bootstrap(){try{assertConfig();const r=await jsonp('bootstrap');state.containers=r.containers||[];state.connection=r.connection||null;setOnline(true,state.connection?.spreadsheetName);renderContainers();}catch(e){setOnline(false);error(e)}}
function assertConfig(){if(!C.API_URL||C.API_URL.includes('PEGA_AQUI'))throw Error('Falta pegar la URL /exec de Apps Script en config.js');}
function renderContainers(){ $('containerSelect').innerHTML='<option value="">Selecciona…</option>'+state.containers.map(c=>`<option value="${c.ID_CONTENEDOR}">${esc(c.REFERENCIA_CONTENEDOR)}</option>`).join(''); }
async function createContainer(){try{const reference=$('containerRef').value.trim();if(!reference)throw Error('Escribe la referencia del contenedor.');busy('Creando contenedor…');const r=await post('createContainer',{reference,purchaseOrder:$('purchaseOrder').value});state.containers.push(r.container);renderContainers();$('containerSelect').value=r.container.ID_CONTENEDOR;$('newContainerCard').classList.add('hidden');toast('Contenedor creado');}catch(e){error(e)}finally{busy(false)}}
async function joinTeam(){try{const person=$('person').value.trim(),teamName=$('teamName').value.trim(),containerId=$('containerSelect').value;if(!person||!teamName||!containerId)throw Error('Completa nombre, equipo y contenedor.');busy('Abriendo equipo…');const r=await post('openTeam',{person,teamName,containerId});localStorage.setItem('validatorName',person);state.container=state.containers.find(c=>c.ID_CONTENEDOR===containerId);state.team=r.team;show('screenPallets');$('containerName').textContent=state.container.REFERENCIA_CONTENEDOR;$('teamLabel').textContent=state.team.NOMBRE_EQUIPO;await loadPallets();}catch(e){error(e)}finally{busy(false)}}
async function loadPallets(){const r=await jsonp('listPallets',{containerId:state.container.ID_CONTENEDOR,teamId:state.team.ID_EQUIPO});$('palletList').innerHTML=(r.pallets||[]).map(p=>`<div class="list-row"><div class="thumb" style="display:grid;place-items:center">📦</div><div><div class="row-title">${esc(p.CODIGO_TARIMA)}</div><div class="row-meta">ID ${esc(p.ID_TARIMA)} · ${esc(p.ESTADO)} · ${esc(p.CREADO_POR)}</div></div><button class="row-action" data-pallet="${p.ID_TARIMA}">›</button></div>`).join('');document.querySelectorAll('[data-pallet]').forEach(b=>b.onclick=()=>openPallet(b.dataset.pallet));}
async function createPallet(){try{busy('Generando tarima…');const r=await post('createPallet',{containerId:state.container.ID_CONTENEDOR,teamId:state.team.ID_EQUIPO,person:$('person').value});await openPallet(r.pallet.ID_TARIMA);}catch(e){error(e)}finally{busy(false)}}
async function openPallet(id){state.pallet={ID_TARIMA:id};show('screenCapture');await refreshPallet();clearInterval(state.timer);state.timer=setInterval(refreshPallet,C.REFRESH_MS);}
async function refreshPallet(){if(!state.pallet)return;try{const r=await jsonp('getPallet',{palletId:state.pallet.ID_TARIMA,teamId:state.team.ID_EQUIPO});state.pallet=r.pallet;state.captures=r.captures||[];renderPallet(r);}catch(e){$('syncText').textContent='Sin conexión';}}
function renderPallet(r){$('palletCode').textContent=r.pallet.CODIGO_TARIMA;$('palletIdLabel').textContent='ID '+r.pallet.ID_TARIMA;$('palletStatus').textContent=r.pallet.ESTADO;$('boxTotal').textContent=r.totals.boxes;$('pieceTotal').textContent=r.totals.pieces;$('syncText').textContent='Actualizado '+new Date().toLocaleTimeString();const open=r.pallet.ESTADO==='EN PROCESO';$('captureCard').classList.toggle('hidden',!open);$('finishBtn').classList.toggle('hidden',!open);$('captureList').innerHTML=state.captures.map(x=>`<div class="list-row"><img class="thumb" src="${escAttr(x.FOTO_ITEM_URL)}"><div><div class="row-title">${esc(x.DESCRIPCION)}</div><div class="row-meta">Caja ${x.NUMERO_CAJA} · ${x.PIEZAS_CAJA} pzas · ${esc(x.REFERENCIA_INTERNA||x.EAN)}<br>${esc(x.VALIDADOR)}</div></div>${open?`<button class="row-action edit-record" data-id="${x.ID_CAPTURA}">✎</button>`:''}</div>`).join('');document.querySelectorAll('.edit-record').forEach(b=>b.onclick=()=>editCapture(b.dataset.id));}
function editCapture(id){const x=state.captures.find(r=>r.ID_CAPTURA===id),map={captureId:'ID_CAPTURA',internalRef:'REFERENCIA_INTERNA',ean:'EAN',description:'DESCRIPCION',pieces:'PIEZAS_CAJA',color:'COLOR',size:'TALLA',height:'ALTO_CM',length:'LARGO_CM',width:'ANCHO_CM',notes:'OBSERVACIONES'};fields.forEach(f=>$(f).value=x[map[f]]||'');state.photos.item='';state.photos.master='';$('captureTitle').textContent='Editar caja '+x.NUMERO_CAJA;$('captureCard').scrollIntoView({behavior:'smooth'});}
async function saveCapture(){try{const payload={captureId:$('captureId').value,palletId:state.pallet.ID_TARIMA,teamId:state.team.ID_EQUIPO,person:$('person').value,internalRef:$('internalRef').value,ean:$('ean').value,description:$('description').value,pieces:$('pieces').value,color:$('color').value,size:$('size').value,height:$('height').value,length:$('length').value,width:$('width').value,notes:$('notes').value,itemPhoto:state.photos.item,masterPhoto:state.photos.master};if(!payload.internalRef.trim()&&!payload.ean.trim())throw Error('Escanea o escribe la referencia interna o el EAN.');if(!payload.description.trim()||Number(payload.pieces)<1)throw Error('Completa descripción y piezas.');if(!payload.captureId&&(!payload.itemPhoto||!payload.masterPhoto))throw Error('Toma las dos fotografías obligatorias.');optimistic(payload);busy('Guardando caja y fotografías…');await post('saveCapture',payload,90000);clearForm();await refreshPallet();toast('Caja guardada');}catch(e){error(e);await refreshPallet()}finally{busy(false)}}
function optimistic(p){state.captures.push({ID_CAPTURA:'TEMP',DESCRIPCION:p.description,PIEZAS_CAJA:p.pieces,REFERENCIA_INTERNA:p.internalRef,EAN:p.ean,VALIDADOR:p.person,FOTO_ITEM_URL:p.itemPhoto,NUMERO_CAJA:'…'});renderPallet({pallet:state.pallet,captures:state.captures,totals:{boxes:state.captures.length,pieces:state.captures.reduce((n,x)=>n+Number(x.PIEZAS_CAJA||0),0)}});}
async function finalizePallet(){if(!confirm('¿Finalizar y bloquear esta tarima?'))return;try{busy('Consolidando tarima…');await post('finalizePallet',{palletId:state.pallet.ID_TARIMA,teamId:state.team.ID_EQUIPO,person:$('person').value},90000);await refreshPallet();toast('Tarima finalizada');}catch(e){error(e)}finally{busy(false)}}
function showPallets(){clearInterval(state.timer);state.pallet=null;show('screenPallets');loadPallets().catch(error)}function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.add('hidden'));$(id).classList.remove('hidden');window.scrollTo(0,0)}
function clearForm(){fields.forEach(f=>$(f).value='');state.photos={item:'',master:''};['item','master'].forEach(k=>$(`${k}Preview`).innerHTML='<span>Sin foto</span>');$('captureTitle').textContent='Capturar caja'}
async function loadFile(file,type){if(!file)return;state.photos[type]=await compress(file);preview(type,state.photos[type]);}
async function openPhotoCamera(type){state.cameraMode='photo';state.cameraTarget=type;$('cameraHint').textContent='Fotografía de '+(type==='item'?'artículo':'caja máster');$('snapBtn').classList.remove('hidden');await openCamera();}
async function openScanner(target){state.cameraMode='scan';state.cameraTarget=target;$('cameraHint').textContent='Centra el código dentro del recuadro';$('snapBtn').classList.add('hidden');try{if('BarcodeDetector'in window){await openCamera();scanLoop();return}if(!window.ZXingBrowser)throw Error('No se cargó el lector de códigos');$('cameraModal').classList.remove('hidden');const reader=new ZXingBrowser.BrowserMultiFormatReader();state.zxingControls=await reader.decodeFromVideoDevice(undefined,$('cameraVideo'),(result,err,controls)=>{if(result){$(state.cameraTarget).value=result.getText();navigator.vibrate?.(100);controls.stop();state.zxingControls=null;closeCamera();toast('Código escaneado')}});}catch(e){closeCamera();toast('La cámara continua fue bloqueada. Toma una foto clara del código.');$('scanUpload').value='';$('scanUpload').click()}}
async function decodeScanPhoto(file){if(!file)return;try{busy('Leyendo código…');if(!window.ZXingBrowser)throw Error('No se cargó el lector');const data=await compress(file),reader=new ZXingBrowser.BrowserMultiFormatReader(),result=await reader.decodeFromImageUrl(data);$(state.cameraTarget).value=result.getText();navigator.vibrate?.(100);toast('Código escaneado');}catch(e){error(new Error('No se detectó un código. Acerca la cámara y evita reflejos.'))}finally{busy(false)}}
async function openCamera(){try{$('cameraModal').classList.remove('hidden');state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280}},audio:false});$('cameraVideo').srcObject=state.stream;}catch(e){closeCamera();throw Error('No se pudo abrir la cámara. Revisa el permiso del navegador.')}}
async function scanLoop(){const detector=new BarcodeDetector({formats:['ean_13','ean_8','code_128','code_39','itf','qr_code','data_matrix']});while(state.stream&&state.cameraMode==='scan'){try{const codes=await detector.detect($('cameraVideo'));if(codes.length){$(state.cameraTarget).value=codes[0].rawValue;navigator.vibrate?.(100);closeCamera();toast('Código escaneado');return}}catch(e){}await wait(150)}}
function snapPhoto(){const v=$('cameraVideo'),c=document.createElement('canvas'),max=1100,scale=Math.min(1,max/Math.max(v.videoWidth,v.videoHeight));c.width=v.videoWidth*scale;c.height=v.videoHeight*scale;c.getContext('2d').drawImage(v,0,0,c.width,c.height);const data=c.toDataURL('image/jpeg',.72);state.photos[state.cameraTarget]=data;preview(state.cameraTarget,data);closeCamera();}
function closeCamera(){if(state.zxingControls){try{state.zxingControls.stop()}catch(e){}state.zxingControls=null}if(state.stream)state.stream.getTracks().forEach(t=>t.stop());state.stream=null;$('cameraModal').classList.add('hidden')}
function preview(type,data){$(`${type}Preview`).innerHTML=`<img src="${data}" alt="Vista previa">`}
function compress(file){return new Promise((res,rej)=>{const img=new Image(),u=URL.createObjectURL(file);img.onload=()=>{const max=1100,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=img.width*s;c.height=img.height*s;c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',.72))};img.onerror=rej;img.src=u})}
async function post(action,payload,timeout=60000){const tx=crypto.randomUUID();submitPost(action,tx,payload);const start=Date.now();while(Date.now()-start<timeout){const r=await jsonp('job',{tx});if(r.status==='done'){if(!r.ok)throw Error(r.error||'Error de servidor');return r.result}await wait(500)}throw Error('La operación tardó demasiado. Revisa Apps Script.');}
function submitPost(action,tx,payload){const frame=document.createElement('iframe'),form=document.createElement('form');frame.name='post_'+tx;frame.hidden=true;form.hidden=true;form.method='POST';form.action=C.API_URL;form.target=frame.name;Object.entries({action,tx,payload:JSON.stringify(payload)}).forEach(([name,value])=>{const input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;form.appendChild(input)});document.body.append(frame,form);form.submit();setTimeout(()=>{form.remove();frame.remove()},120000)}
function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb='cb_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script'),timer=setTimeout(()=>done(new Error('Sin respuesta del servidor')),20000);window[cb]=data=>done(null,data);function done(err,data){clearTimeout(timer);delete window[cb];s.remove();err?reject(err):data?.ok===false?reject(new Error(data.error||'Error')):resolve(data)}const q=new URLSearchParams({action,prefix:cb,...params,_:Date.now()});s.onerror=()=>done(new Error('No se pudo conectar con Apps Script'));s.src=C.API_URL+'?'+q;s.async=true;document.body.appendChild(s)})}
function busy(text){$('busy').classList.toggle('hidden',!text);if(text)$('busyText').textContent=text}function toast(m){$('toast').textContent=m;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),3500)}function error(e){console.error(e);toast(e.message||String(e))}function setOnline(v,label=''){ $('online').textContent=v?'● '+(label||'Sincronizado'):'● Sin conexión';$('online').style.color=v?'#9be5c8':'#ff9b9b'}function wait(ms){return new Promise(r=>setTimeout(r,ms))}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escAttr(v){return esc(v)}
